-- DEPRECATED: This file has been consolidated into supabase/schema.sql
-- (the canonical, client-matching schema with secure RLS policies).
--
-- Run supabase/schema.sql in your Supabase SQL Editor instead.
-- The previous version of this file diverged from the API service
-- (different column names/shapes) and enabled authenticated-only writes
-- while the app does not yet create Supabase Auth sessions, which would
-- have silently broken all driver reports and community posts.
